# Generated by Django 6.0.3 on 2026-03-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendor",
            old_name="avatar",
            new_name="logo",
        ),
    ]
