# Generated by Django 6.0.3 on 2026-03-09 17:48

import django.core.validators
import django.db.models.deletion
import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                (
                    "code",
                    models.IntegerField(
                        default=utils.helper.generate_code,
                        validators=[
                            django.core.validators.MinValueValidator(100000),
                            django.core.validators.MaxValueValidator(999999),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(default=utils.helper.get_expiration_time),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("SIGNUP", "Signup"),
                            ("RESET_PASSWORD", "Reset Password"),
                            ("FORGET_PASSWORD", "Forget Password"),
                        ],
                        default="SIGNUP",
                        max_length=20,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name="vendorstats",
            old_name="vendor",
            new_name="tenant",
        ),
        migrations.RemoveField(
            model_name="order",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="sponsoredad",
            name="product",
        ),
        migrations.RemoveField(
            model_name="sponsoredad",
            name="tenant",
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="tenant",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.vendor"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tenant",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.vendor"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="base.vendor",
            ),
            preserve_default=False,
        ),
    ]
