# Generated by Django 6.0.3 on 2026-03-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactmessage",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="tenant",
        ),
    ]
