# Generated by Django 6.0.3 on 2026-03-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_avatar_vendor_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsoredad",
            name="budget",
        ),
    ]
