# Generated by Django 6.0.3 on 2026-03-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_contactmessage_is_read_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storecategory",
            name="image",
            field=models.ImageField(blank=True, upload_to="categories/images/"),
        ),
    ]
