# Generated by Django 6.0.3 on 2026-04-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_product_telegram_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="telegram_id",
        ),
        migrations.AddField(
            model_name="customuser",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
