# Generated by Django 6.0.3 on 2026-03-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_sponsoredad_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsoredad",
            name="days_count",
        ),
        migrations.AlterField(
            model_name="sponsoredad",
            name="status",
            field=models.CharField(
                choices=[("active", "نشط"), ("inactive", "غير نشط")],
                default="active",
                max_length=20,
            ),
        ),
    ]
