# Generated by Django 6.0.3 on 2026-03-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_storecategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsoredad",
            name="vendor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                to="base.vendor",
            ),
            preserve_default=False,
        ),
    ]
