# Generated by Django 6.0.3 on 2026-03-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_sponsoredad_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
