# Generated by Django 6.0.3 on 2026-03-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_remove_sponsoredad_days_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="is_active",
        ),
    ]
