# Generated by Django 6.0.3 on 2026-03-26 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_vendor_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsoredad",
            name="created_at",
        ),
        migrations.AddField(
            model_name="sponsoredad",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 3, 26, 16, 41, 3, 711249, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
