# Generated by Django 6.0.3 on 2026-03-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_customuser_is_verified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sponsoredad",
            old_name="vendor",
            new_name="tenant",
        ),
    ]
