# Generated by Django 6.0.3 on 2026-03-27 10:36

import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_order_discount_amount_coupon_order_coupon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="coupon",
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(
                default=utils.helper.generate_coupon_code, max_length=8
            ),
        ),
    ]
