# Generated by Django 6.0.3 on 2026-03-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_remove_order_coupon_alter_coupon_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="orders_to_receive",
            field=models.IntegerField(default=50),
        ),
    ]
