# Generated by Django 6.0.3 on 2026-03-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_coupon_orders_to_receive"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="recipient_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]