from django.urls import include
from django.urls import path
from .views import base, moderators, vendor


basePatterns = [
    path('', base.HomeView.as_view(), name='home'),
    path('login/', base.LoginView.as_view(), name='login'),
    path('logout/', base.LogoutView.as_view(), name='logout'),
    path('signup/', base.BuyerSignupView.as_view(), name='buyer_signup'),
    path('otp/', base.OtpCodeView.as_view(), name='otp'),
    path('verify-otp/', base.VerifyOtpView.as_view(), name='verify_otp'),
    path('vendors/', base.VendorsView.as_view(), name='vendors'),
    path('categories/', base.CategoriesView.as_view(), name='category_list'),
    path('offers/', base.OfferListView.as_view(), name='offer_list'),
    path('ads/', base.AdListView.as_view(), name='ad_list'),
    path('products/', base.ProductListView.as_view(), name='product_list'),
    path('products/<int:product_id>/', base.ProductDetailView.as_view(), name='product'),
    path('products/<int:product_id>/rate/', base.RateProductView.as_view(), name='rate_product'),
    path('cart/', base.CartHTMXView.as_view(), name='cart_htmx'),
    path('cart/add/<int:product_id>/', base.AddToCartView.as_view(), name='add_to_cart'),
    path('cart/remove/<int:product_id>/', base.RemoveFromCartView.as_view(), name='remove_from_cart'),
    path('cart/update/<int:product_id>/', base.UpdateCartView.as_view(), name='update_cart'),
    path('favorites/toggle/<int:product_id>/', base.ToggleFavoriteView.as_view(), name='toggle_favorite'),
    path('favorites/remove/<int:product_id>/', base.RemoveFavoriteView.as_view(), name='remove_favorite'),
    path('account/update/', base.AccountUpdateView.as_view(), name='account_update'),
    path('change-password/', base.ChangePasswordView.as_view(), name='change_password'),
    # path('reset-password/', base.ResetPasswordView.as_view(), name='reset_password'),
    path('checkout/<int:vendor_id>/', base.CheckoutView.as_view(), name='checkout'),
    path('checkout/<int:vendor_id>/validate-coupon/', base.ValidateCouponHTMXView.as_view(), name='validate_coupon'),
    path('checkout/<int:vendor_id>/remove-coupon/', base.RemoveCouponHTMXView.as_view(), name='remove_coupon'),
    path('checkout/success' , base.CheckoutSuccess.as_view() , name="checkout_success"),
    path('404/' , base.handler404.as_view() , name="404"),
    path('500/' , base.handler500.as_view() , name="500"),
]

moderatorPatterns = [
    path('', moderators.ModeratorStatsView.as_view(), name='moderator_stats'),
    path('login/', moderators.ModeratorLoginView.as_view(), name='moderator_login'),
    path('logout/', moderators.ModeratorLogoutView.as_view(), name='moderator_logout'),
    path('vendors/', moderators.ModeratorVendorsView.as_view(), name='moderator_vendors'),
    path('vendors/update/<int:pk>/', moderators.ModeratorVendorUpdateView.as_view(), name='moderator_vendor_update'),
    path('vendors/delete/<int:pk>/', moderators.ModeratorVendorDeleteView.as_view(), name='moderator_vendor_delete'),
    path('list/', moderators.ModeratorListView.as_view(), name='moderator_list'),
    path('update/<int:pk>/', moderators.ModeratorUpdateView.as_view(), name='moderator_update'),
    path('add/', moderators.ModeratorAddView.as_view(), name='moderator_add'),
    path('delete/<int:pk>/', moderators.ModeratorDeleteView.as_view(), name='moderator_delete'),
    path('categories/', moderators.ModeratorCategoriesView.as_view(), name='moderator_categories'),
    path('categories/add/', moderators.ModeratorCategoryAddView.as_view(), name='moderator_category_add'),
    path('categories/update/<int:pk>/', moderators.ModeratorCategoryUpdateView.as_view(), name='moderator_category_update'),
    path('categories/delete/<int:pk>/', moderators.ModeratorCategoryDeleteView.as_view(), name='moderator_category_delete'),
    path('messages/', moderators.ModeratorMessagesView.as_view(), name='message_list'),
    path('messages/update/<int:pk>/', moderators.ModeratorMessageUpdateView.as_view(), name='message_update'),
    path('messages/delete/<int:pk>/', moderators.ModeratorMessageDeleteView.as_view(), name='message_delete'),
]

vendorPatterns = [
    path('dashboard/', vendor.VendorDashboardView.as_view(), name='vendor_dashboard'),
    path('offers/', vendor.OffersListView.as_view(), name='vendor_offers'),
    path('offers/add/', vendor.OfferAddView.as_view(), name='offer_add'),
    path('offers/update/<int:pk>/', vendor.OfferUpdateView.as_view(), name='offer_update'),
    path('offers/delete/<int:pk>/', vendor.OfferDeleteView.as_view(), name='offer_delete'),
    path('ads/', vendor.AdsListView.as_view(), name='vendor_ads'),
    path('ads/add/', vendor.AdAddView.as_view(), name='ad_add'),
    path('ads/update/<int:pk>/', vendor.AdUpdateView.as_view(), name='ad_update'),
    path('ads/delete/<int:pk>/', vendor.AdDeleteView.as_view(), name='ad_delete'),
    path('categories/', vendor.CategoriesListView.as_view(), name='vendor_categories'),
    path('categories/add/', vendor.CategoryAddView.as_view(), name='category_add'),
    path('categories/update/<int:pk>/', vendor.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', vendor.CategoryDeleteView.as_view(), name='category_delete'),
    path('products/', vendor.ProductsListView.as_view(), name='vendor_products'),
    path('products/add/', vendor.ProductAddView.as_view(), name='product_add'),
    path('products/update/<int:pk>/', vendor.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', vendor.ProductDeleteView.as_view(), name='product_delete'),
    path('orders/', vendor.OrdersListView.as_view(), name='vendor_orders'),
    path('orders/update/<int:pk>/', vendor.OrderUpdateView.as_view(), name='order_update'),
    path('orders/delete/<int:pk>/', vendor.OrderDeleteView.as_view(), name='order_delete'),
    path('store/<int:pk>/', vendor.VendorStoreView.as_view(), name='vendor_store'),
    path('coupons/', vendor.VendorCouponsView.as_view(), name='vendor_coupons'),
    path('coupons/add/', vendor.VendorCouponAddView.as_view(), name='coupon_add'),
    path('coupons/update/<int:pk>/', vendor.VendorCouponUpdateView.as_view(), name='coupon_update'),
    path('coupons/delete/<int:pk>/', vendor.VendorCouponDeleteView.as_view(), name='coupon_delete'),
    path('signup/', vendor.VendorSignupView.as_view(), name='vendor_signup'),
    path('settings/', vendor.VendorSettingsView.as_view(), name='vendor_settings'),
]

urlpatterns = [
    path('', include(basePatterns)),
    path('moderator/', include(moderatorPatterns)),
    path('vendor/', include(vendorPatterns))
]
